name: Facebook Live Streamer

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg and Latest yt-dlp
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          python3 -m pip install -U --force-reinstall https://github.com/yt-dlp/yt-dlp/archive/master.tar.gz

      - name: Create Cookies File
        env:
          COOKIES_DATA: ${{ secrets.FB_COOKIES }}
        run: |
          echo "$COOKIES_DATA" > cookies.txt

      - name: Stream Video to Facebook Live
        env:
          STREAM_URL: ${{ secrets.FB_LIVE_URL }}
          FB_PAGE_URL: "https://www.facebook.com/share/1KQLcMfA6K/"
        run: |
          DIRECT_URL=$(yt-dlp --cookies cookies.txt \
            --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
            -g "$FB_PAGE_URL")
          
          ffmpeg -re -i "$DIRECT_URL" \
            -c:v libx264 -preset superfast -maxrate 3000k -bufsize 6000k \
            -pix_fmt yuv420p -g 60 -c:a aac -b:a 128k -ar 44100 \
            -f flv "$STREAM_URL"
