name: Facebook Live

on:
  workflow_dispatch:

jobs:
  facebook-live:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip
          pip3 install -U gdown

      - name: Download video from Google Drive
        run: |
          gdown "https://drive.google.com/uc?id=1LZICk4PJTgM6pw5xoEDq1A7wwAPRU1y8" \
            -O video.mp4

          ls -lh video.mp4

      - name: Start Facebook Live
        env:
          FB_STREAM_KEY: ${{ secrets.FB_STREAM_KEY }}
        run: |
          ffmpeg \
            -re \
            -stream_loop -1 \
            -i video.mp4 \
            -vf "scale=-2:720,fps=30" \
            -c:v libx264 \
            -preset veryfast \
            -pix_fmt yuv420p \
            -b:v 3000k \
            -maxrate 3000k \
            -bufsize 6000k \
            -g 60 \
            -keyint_min 60 \
            -sc_threshold 0 \
            -c:a aac \
            -b:a 128k \
            -ar 44100 \
            -f flv \
            "rtmps://live-api-s.facebook.com:443/rtmp/$FB_STREAM_KEY"
